# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Build library

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    - name: Build and pack
      working-directory: ./src
      run: dotnet pack --configuration Release -p:EmbedUntrackedSources=true -p:ContinuousIntegrationBuild=true -p:PublishRepositoryUrl=true -p:ReleaseBuild=true LibTopoART.Compatibility.fsproj

    - uses: actions/upload-artifact@v4
      with:
        name: NuGetPackage
        path: /home/runner/work/LibTopoART.Compatibility/LibTopoART.Compatibility/src/bin/Release/LibTopoART.Compatibility.0.*.?.nupkg
